name: Build GApps for Android TV

on: 
  workflow_dispatch:
    inputs:
      ARCH:
        description: 'ARCH: Which arch you want build to.'
        required: true
        default: 'arm64'
      ANDROID_VERSION:
        description: 'ANDROID_VERSION: Which Android version you want build to. Get more information at README.'
        required: true
        default: '12.1.0'
      BRANCH:
        description: 'BRANCH: Which Android version you want build to. Get more information at README.'
        required: true
        default: 'sigma'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prepare the environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential curl git lz4 patch python3 repo squashfs-tools wget xz-utils zip

    - name: Clone MindTheGapps For AndroidTV
      run: |
        git clone -b ${{ github.event.inputs.BRANCH }} --single-branch https://gitlab.com/MindTheGapps/vendor_gapps_tv.git

    - name: Build GApps for Android TV
      run: |
        cd vendor_gapps_tv
        make gapps_tv_${{ github.event.inputs.ARCH }} -j$(nproc)

    - name: Creating Release GApps for Android TV
      uses: softprops/action-gh-release@v1
      with:
       files: |
        vendor_gapps_tv/out/MindTheGapps-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.ARCH }}-ATV-*.zip
       name: Mind the GApps For ATV
       tag_name: ATV-${{ github.event.inputs.ANDROID_VERSION }}_${{ github.event.inputs.ARCH }}
       body: All Mind the GApps versions of ${{ github.event.inputs.ARCH }}_android-${{ github.event.inputs.ANDROID_VERSION }} for Android TV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
